### EXPERIMENT 1
Objective : Introduction to `Python` and its `various applications`

In [ ]:
import numpy as np
import pandas as pf
import matplotlib.pyplot as plt
from scipy import sparse

In [ ]:
vector_row=np.array([1,2,3])
print(vector_row)


[1 2 3]


In [ ]:
vector_column=np.array([[1],[2],[3]])
print(vector_column)

[[1]
 [2]
 [3]]


In [ ]:
### creating a matrix
matrix = np.array([[1,2,23],[3,4,5]])
matrix

array([[ 1,  2, 23],
       [ 3,  4,  5]])

In [ ]:
### creating a sparse matrix
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix)

[[ 1  2 23]
 [ 3  4  5]]


In [ ]:
# create a large matrix
mat1 = np.array([[1,2,2,2,1,1,12,21,3,2],[1,1,1,1,1,1,1,1,1,1]])
mat1
spa = sparse.csr_matrix(mat1)
spa

<2x10 sparse matrix of type '<class 'numpy.int64'>'
	with 20 stored elements in Compressed Sparse Row format>

In [ ]:
#create a new array
vector = np.array([1,22,1,212,2,121,231,1,1])

In [ ]:
vector.size

9

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

(9,)

In [ ]:
vector[::]

array([  1,  22,   1, 212,   2, 121, 231,   1,   1])

In [ ]:
vector[::-1]

array([  1,   1, 231, 121,   2, 212,   1,  22,   1])

In [ ]:
vector[1:4]

array([ 22,   1, 212])

In [ ]:
vector.std()

90.98080112221209

In [ ]:
# calculating mean
vector.mean()


65.77777777777777

In [ ]:
np.average(vector)

65.77777777777777

In [ ]:
vector.var()

8277.506172839507

In [ ]:
# calulating sum
vector.sum()

592

In [ ]:
# finding maximum number
np.max(vector)

231

In [ ]:
#calculating variance
var = np.mean(abs(vector - vector.mean())**2)
var

8277.506172839507

In [ ]:
# add 1000 to matrix
add_1000 = lambda i : i + 1000
vecadd1000 = np.vectorize(add_1000)
vecadd1000(vector)

array([1001, 1022, 1001, 1212, 1002, 1121, 1231, 1001, 1001])

In [ ]:
#creatng a matrix
matrix2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
matrix2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
matrix2.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
np.transpose(matrix2)

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [ ]:
# linear algebra
a = np.array([[5,3],[-6,-4]])

In [ ]:
from numpy import linalg

In [ ]:
print(np.linalg.inv(a))

[[ 2.   1.5]
 [-3.  -2.5]]


In [ ]:
#CREATE  A NUMPY ARRAY
np.array([1,2,3])

array([1, 2, 3])

### Post Lab Exercise

In [ ]:
# Q1. Write a program to check whether all elements in an array are non zero
arr = np.array([1, 2, 3, 4])

In [ ]:
if np.all(arr):
  print("All elements are non-zero.")
else:
  print("There are zero elements in the array.")

All elements are non-zero.


In [ ]:
# Q2. Write a program to create a 2X2 matrix of ones and adding a border around it with zeros
arr = np.ones((2, 2))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Q3. Write a program to multiply a randomly generated 4X3 size matrix to randomly generated 3X5 size matrix.
arr1 = np.random.rand(4, 3)
arr2 = np.random.rand(3, 5)
result = np.dot(arr1, arr2)
print(result)

[[0.96617513 0.64851337 1.74676008 0.38330398 0.94162276]
 [0.57020505 0.41072535 1.44034144 0.406619   0.92287457]
 [1.18768913 0.74887856 2.08435307 0.50929337 1.13934318]
 [0.89311297 0.55206492 1.57149819 0.40176671 0.87030856]]


In [ ]:
# Q4. Write a program to solve the system of equations x0 + 2 * x1 = 1 and 3 *x0 + 5 * x1 = 2. [Hint: Use np.linalg.solve]
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
x = np.linalg.solve(a, b)
print(x)

[-1.  1.]
